Edit of v1.1 documentation
pivotal-cf/docs-spring-cloud-dataflow-k8s pull request #27
Opened 2020-10-19 17:08 UTC by fifthposition

2020-10-22 18:19 UTC, sabbyanandan requested changes
Lots of great details and edits! Thanks, @fifthposition!

2020-10-22 18:19 UTC, sabbyanandan commented on docs-content/connecting-scdf-for-kubernetes.html.md.erb
> +* The Spring Cloud Data Flow shell; [download from the Spring Release Maven repository](https://repo.spring.io/libs-release/org/springframework/cloud/spring-cloud-dataflow-shell/2.6.3/spring-cloud-da
I wonder if the version can be parameterized, so the download link doesn't go outdated. cc:/ @trisberg

2020-10-22 18:19 UTC, sabbyanandan commented on docs-content/getting-started-pipeline.html.md.erb
> +For more information about the application starters, see the [Register Supported Applications and Tasks](https://docs.spring.io/spring-cloud-dataflow/docs/current/reference/htmlsingle/#supported-apps
Glad we changed the URL to `current`; right thing to do.

2020-10-22 18:19 UTC, sabbyanandan commented on docs-content/index.html.md.erb
> +            <td>v1.1.3</td>
We are preparing for 1.1.4 now.

2020-10-22 18:19 UTC, sabbyanandan commented on docs-content/installing-command-line-tools.html.md.erb
> +1. Download the 3.3 binary file from the project <a href="https://github.com/mikefarah/yq/releases/tag/3.3.0">Releases</a> page on GitHub.
Should these version be updated? cc:/ @trisberg

2020-10-22 18:19 UTC, sabbyanandan commented on docs-content/preparing-to-install-scdf-for-kubernetes.html.md.erb
> +* The following command-line utilities:
Ah, versions defined with suggestions here. Perhaps the same comment on the previous areas where we point to a specific release of `yq`? cc: @trisberg

2020-10-23 00:24 UTC, trisberg commented on docs-content/index.html.md.erb
> +            <td>v1.1.3</td>
Right, we'll have to update once we are ready for GA of 1.1.4

2020-10-23 00:25 UTC, trisberg commented on docs-content/connecting-scdf-for-kubernetes.html.md.erb
> +* The Spring Cloud Data Flow shell; [download from the Spring Release Maven repository](https://repo.spring.io/libs-release/org/springframework/cloud/spring-cloud-dataflow-shell/2.6.3/spring-cloud-da
That would be nice, I've been updating it for every release.

2020-10-23 00:27 UTC, trisberg commented on docs-content/installing-command-line-tools.html.md.erb
> +1. Download the 3.3 binary file from the project <a href="https://github.com/mikefarah/yq/releases/tag/3.3.0">Releases</a> page on GitHub.
We should change the link to be https://github.com/mikefarah/yq/releases

2020-10-26 16:41 UTC, fifthposition commented on docs-content/connecting-scdf-for-kubernetes.html.md.erb
> +* The Spring Cloud Data Flow shell; [download from the Spring Release Maven repository](https://repo.spring.io/libs-release/org/springframework/cloud/spring-cloud-dataflow-shell/2.6.3/spring-cloud-da
I think the easiest approach here would be to move over the docs to AsciiDoc, but I don't know that we can do that with current tooling. Something for me to look into, as it’s been years since I last seriously thought about it.

2020-10-26 16:43 UTC, sabbyanandan approved these changes
Let's go!

2020-10-26 16:43 UTC, merged

2020-10-26 16:43 UTC, sabbyanandan commented
@fifthposition: Thank you so much for all the incredible doc polishing / updates!

2020-10-26 16:52 UTC, fifthposition commented
My pleasure! 😃