Added docs for progress bar
pivotal-cf/docs-spring-cloud-dataflow-k8s pull request #37
Opened 2021-05-30 17:59 UTC by cppwfs

resolves #36

Had issues installing the tools for rendering the docs.   So these changes have not been validated against that tooling.

2021-06-04 19:07 UTC, fifthposition approved these changes

2021-06-04 19:07 UTC, fifthposition commented on docs-content/pro-features/task-execution-progress.md.erb
> +In addition to the task execution status, SCDF Pro server adds support for displaying a percent complete progress indicator on the task execution detail page.
I would say "displaying a progress indicator".

2021-06-04 19:07 UTC, fifthposition commented on docs-content/pro-features/task-execution-progress.md.erb
> +In addition to the task execution status, SCDF Pro server adds support for displaying a percent complete progress indicator on the task execution detail page.
If "Task Execution" or "Task Execution Detail" is part of the page title, it should be capitalized (as it would be on the page).

2021-06-04 21:22 UTC, cppwfs commented on docs-content/pro-features/task-execution-progress.md.erb
> +Spring Cloud Data Flow OSS allows users to track each execution status for a task definition via the task execution detail page.
Thanks for the feedback.   Updated based on comments.

2021-06-04 21:22 UTC, cppwfs commented on docs-content/pro-features/task-execution-progress.md.erb
> +In addition to the task execution status, SCDF Pro server adds support for displaying a percent complete progress indicator on the task execution detail page.
Updated based on comments.

2021-06-08 15:45 UTC, sabbyanandan commented
@jvalkeal @ilayaperumalg: Are you both good with this also?

2021-06-09 11:34 UTC, ilayaperumalg commented
The changes scoped for this PR look good. 
I have a question around mapping the Pro features for K8s and TAS. Where can I see the change which converts container vs maven artifact when it comes to K8s vs TAS? 
Also, I'd like to make some changes on the versions of the apps being used in the documentation. I will have a separate PR for the same.

2021-06-10 16:45 UTC, sabbyanandan requested changes

2021-06-10 16:45 UTC, sabbyanandan commented on docs-content/pro-features/task-execution-progress.md.erb
> +title: Task Execution Progress Bar in VMware Spring Cloud® Data Flow for Kubernetes
```suggestion
title: Task Execution Progress Indicator
```

2021-06-10 16:46 UTC, merged

2021-06-10 16:46 UTC, sabbyanandan commented on docs-content/pro-features/task-execution-progress.md.erb
> +title: Task Execution Progress Bar in VMware Spring Cloud® Data Flow for Kubernetes
we cannot parameterize titles dynamically with tas vs. k8s, so suggesting a neutral title ..